name = "lithhash/packet"
version = "0.1.23"
description = "Packet, a pragmatic roblox networking library. "
authors = ["LithHash"]
repository = "https://github.com/LithHash/Packet"
license = "MIT"
includes = ["src/*", "README.md", "pesde.toml"]

[target]
environment = "roblox"
build_files = ["src"]
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
